class gm_efai
{
	class efai
	{
		class init {postInit = 1;};   // gm_efai_fnc_init
		class assistantGarbageCollector {};  // gm_efai_fnc_assistantGarbageCollector
		class createFromTemplate {};  // gm_efai_fnc_createFromTemplate
		class counterattack {};       // gm_efai_fnc_counterattack
		class dynamicSimulation {};   // gm_efai_fnc_dynamicSimulation
		class forceTracker {};        // gm_efai_fnc_forceTracker
		class enemyHighlight {};      // gm_efai_fnc_enemyHighlight
		class moveGroup {};           // gm_efai_fnc_moveGroup
		class occupyLocation {};      // gm_efai_fnc_occupyLocation
		class garrison {};            // gm_efai_fnc_garrison
		class paradrop {};            // gm_efai_fnc_paradrop
		class zoneMarkers {};         // gm_efai_fnc_zoneMarkers
		class zoneMarkers_server {};  // gm_efai_fnc_zoneMarkers_server
		class zoneSetup_server {};    // gm_efai_fnc_zoneSetup_server
	};
};