class gm_wfor_shop_inventory
{
	class NATO
	{
		class SmallArms
		{
			displayName = "Small Arms";
			class Weapons
			{
				displayname = "Weapons";
				realm = "cfgWeapons";
				content[] =
				{
					"gm_g3a3_oli", 1000,
					"gm_g3a3a0_gold", 80000,
					"gm_g3a3a0_oli", 1000,
					"gm_g3a3a0_blk", 1000,
					"gm_g3a3a1_ris_blk", 1000,
					"gm_g3a3a1_ris_oli", 1000,
					"gm_g3a4_oli", 1000,
					"gm_g3a4a0_blk", 1000,
					"gm_g3a4a0_oli", 1000,
					"gm_g3a4a1_ris_blk", 1000,
					"gm_g3a4a1_ris_oli", 1000,
					"gm_g3ka4_blk", 1000,
					"gm_g3ka4_oli", 1000,
					"gm_g3ka4a1_ris_blk", 1000,
					"gm_g3sg1_blk", 2000,
					"gm_g3sg1_oli", 2000,
					"gm_sg542_blk", 1300,
					"gm_sg542_oli", 1300,
					"gm_sg542_ris_blk", 1300,
					"gm_sg542_ris_oli", 1300,
					"gm_g36a1_blk", 1200,
					"gm_g36e_blk", 900,
					"gm_c7a1_oli", 800,
					"gm_c7a1_blk", 800,
					"gm_m16a1_blk", 800,
					"gm_m16a2_blk", 800,
					"gm_hk33a2_blk", 800,
					"gm_hk33a3_blk", 800,
					"gm_mpm85_blk", 1200,
					"gm_hk33ka2_blk", 800,
					"gm_hk33ka3_blk", 800,
					"gm_hk33sg1_blk", 1500,
					"gm_hk53a2_blk", 600,
					"gm_hk53a3_blk", 600,
					"gm_sg550_blk", 900,
					"gm_sg550_oli", 900,
					"gm_sg550_ris_blk", 900,
					"gm_sg550_ris_oli", 900,
					"gm_sg551_blk", 600,
					"gm_sg551_oli", 600,
					"gm_sg551_ris_blk", 600,
					"gm_sg551_ris_oli", 600,
					"gm_sg551_swat_blk", 1000,
					"gm_mg3_blk", 1600,
					"gm_g8a1_blk", 1600,
					"gm_g8a2_blk", 1800,
					"gm_mg8a1_blk", 2600,
					"gm_mg8a2_blk", 2800,
					"gm_psg1_blk", 4300,
					"gm_msg90_blk", 4000,
					"gm_msg90a1_blk", 4800,
					"gm_hk512_wud", 800,
					"gm_hk512_ris_wud", 800,
					"gm_mp2a1_blk", 300,
					"gm_mp5a2_blk", 500,
					"gm_mp5a2_blk", 500,
					"gm_mp5a3_surefire_blk", 800,
					"gm_mp5a4_blk", 500,
					"gm_mp5a5_blk", 500,
					"gm_mp5n_blk", 500,
					"gm_mp5n_surefire_blk", 800,
					"gm_mp5nsd1_blk", 800,
					"gm_mp5nsd2_blk", 800,
					"gm_mp5sd2_blk", 700,
					"gm_mp5sd3_blk", 700,
					"gm_mp5sd5_blk", 700,
					"gm_mp5sd6_blk", 700,
					"gm_g11k2_blk", 4000,
					"gm_g11k2_ris_blk", 6000
				};
			};
			class Handguns
			{
				displayname = "Handguns";
				realm = "cfgWeapons";
				content[] =
				{
					"gm_p1_blk", 100,
					"gm_p1sd_blk", 200,
					"gm_m49_blk", 100,
					"gm_p210_blk", 100,
					"gm_p2a1_blk", 125
				};
			};
			class Magazines
			{
				displayname = "Magazines";
				realm = "cfgMagazines";
				content[] =
				{
					"gm_20Rnd_762x51mm_b_t_DM21_g3_blk",     70,
					"gm_20Rnd_762x51mm_b_t_DM21A1_g3_blk",   80,
					"gm_20Rnd_762x51mm_b_t_DM21A2_g3_blk",   80,
					"gm_20Rnd_762x51mm_b_DM111_g3_blk",      100,
					"gm_20Rnd_762x51mm_b_DM41_g3_blk",       110,
					"gm_20Rnd_762x51mm_ap_DM151_g3_blk",     360,

					"gm_20Rnd_762x51mm_B_T_DM21_g3_gold",     500,

					"gm_20Rnd_762x51mm_B_T_DM21_sg542_blk",       180,
					"gm_20Rnd_762x51mm_B_T_DM21A1_sg542_blk",     180,
					"gm_20Rnd_762x51mm_B_T_DM21A2_sg542_blk",     180,
					"gm_20Rnd_762x51mm_B_DM111_sg542_blk",        180,
					"gm_20Rnd_762x51mm_B_DM41_sg542_blk",         180,
					"gm_20Rnd_762x51mm_ap_DM151_sg542_blk",       360,

					"gm_120Rnd_762x51mm_b_t_DM21_mg3_grn",   200,
					"gm_120Rnd_762x51mm_b_t_DM21A1_mg3_grn", 220,
					"gm_120Rnd_762x51mm_b_t_DM21A2_mg3_grn", 240,

					"gm_100Rnd_762x51mm_B_T_DM21_mg8_oli", 200,
					"gm_100Rnd_762x51mm_B_T_DM21A1_mg8_oli", 220,
					"gm_100Rnd_762x51mm_B_T_DM21A2_mg8_oli", 240,

					"gm_30Rnd_556x45mm_b_dm11_g36_blk",      50,
					"gm_30Rnd_556x45mm_b_t_dm21_g36_blk",    50,

					"gm_30Rnd_556x45mm_b_DM11_hk33_blk",     50,
					"gm_30Rnd_556x45mm_b_t_DM21_hk33_blk",   50,
					"gm_40Rnd_556x45mm_b_DM11_hk33_blk",     67,
					"gm_40Rnd_556x45mm_b_t_DM21_hk33_blk",   67,
					"gm_60Rnd_556x45mm_b_DM11_hk33_blk",     100,
					"gm_60Rnd_556x45mm_b_t_DM21_hk33_blk",   100,

					"gm_30Rnd_556x45mm_b_dm11_sg550_brn",    50,
					"gm_30Rnd_556x45mm_b_t_dm21_sg550_brn",  50,

					"gm_20Rnd_556x45mm_b_M855_stanag_gry",   50,
					"gm_20Rnd_556x45mm_b_t_M856_stanag_gry", 50,

					"gm_30Rnd_556x45mm_b_M855_stanag_gry",   55,
					"gm_30Rnd_556x45mm_b_t_M856_stanag_gry", 55,

					"gm_7rnd_12ga_hk512_slug",               20,
					"gm_7rnd_12ga_hk512_pellet",             20,

					"gm_50Rnd_473x33mm_b_dm11_g11_blk",      120,
					"gm_50Rnd_473x33mm_b_t_dm21_g11_blk",    120,

					"gm_30Rnd_9x19mm_b_DM51_mp5_blk",        30,
					"gm_30Rnd_9x19mm_b_DM11_mp5_blk",        30,
					"gm_30Rnd_9x19mm_ap_DM91_mp5_blk",       60,
					"gm_30Rnd_9x19mm_b_DM51_mp5a3_blk",      30,
					"gm_30Rnd_9x19mm_b_DM11_mp5a3_blk",      30,
					"gm_30Rnd_9x19mm_ap_DM91_mp5a3_blk",     60,
					"gm_60Rnd_9x19mm_b_DM51_mp5a3_blk",      60,
					"gm_60Rnd_9x19mm_b_DM11_mp5a3_blk",      60,
					"gm_60Rnd_9x19mm_ap_DM91_mp5a3_blk",     120,

					"gm_32Rnd_9x19mm_b_DM51_mp2_blk",        32,
					"gm_32Rnd_9x19mm_b_DM11_mp2_blk",        32,
					"gm_32Rnd_9x19mm_ap_dm91_mp2_blk",       64,

					"gm_8rnd_9x19mm_b_dm11_p210_blk",        10,
					"gm_8rnd_9x19mm_b_dm51_p210_blk",        10,

					"gm_8rnd_9x19mm_b_dm11_p1_blk",          10,
					"gm_8rnd_9x19mm_b_dm51_p1_blk",          10
				};
			};
			class Launchers
			{
				displayname = "Launchers";
				realm = "cfgWeapons";
				content[] =
				{
					"gm_pzf44_2_oli", 800,
					"gm_pzf84_oli", 1350,
					"gm_fim43_oli", 600,
					"gm_pzf3_blk", 1500,
					"gm_m72a3_oli", 120,
					"gm_hk69a1_blk", 200
				};
			};
			class Rockets
			{
				displayname = "Rockets";
				realm = "cfgMagazines";

				content[] =
				{
					"gm_1Rnd_44x537mm_heat_dm32_pzf44_2",   150,
					"gm_1Rnd_70mm_he_m585_fim43",   100,

					"gm_1rnd_67mm_heat_dm22a1_g3", 60,

					"gm_1Rnd_66mm_heat_m72a3", 80,

					"gm_1Rnd_60mm_heat_dm12_pzf3", 280,
					"gm_1Rnd_60mm_heat_dm22_pzf3", 400,
					"gm_1Rnd_60mm_heat_dm32_pzf3", 80,

					"gm_1Rnd_84x245mm_heat_t_DM12_carlgustaf", 100,
					"gm_1Rnd_84x245mm_heat_t_DM12a1_carlgustaf", 120,
					"gm_1Rnd_84x245mm_heat_t_DM22_carlgustaf", 200,
					"gm_1Rnd_84x245mm_heat_t_DM32_carlgustaf",  250,
					"gm_1Rnd_84x245mm_ILLUM_DM16_carlgustaf",  50
				};
			};
			class Grenades
			{
				displayname = "Grenades";
				realm = "cfgMagazines";

				content[] =
				{
					"gm_handGrenade_frag_m56",  20,

					"gm_handgrenade_conc_dm51",  20,
					"gm_handgrenade_conc_dm51a1",  30,
					"gm_handgrenade_frag_dm51",  20,
					"gm_handgrenade_frag_dm51a1",  30,

					"gm_smokeshell_grn_dm21",  20,
					"gm_smokeshell_org_dm32",  20,
					"gm_smokeshell_red_dm23",  20,
					"gm_smokeshell_wht_dm25",  20,
					"gm_smokeshell_yel_dm26",  20,
					"gm_smokeShell_wht_m77",  20,

					"gm_1rnd_40x46mm_he_dm91", 30,
					"gm_1rnd_40x46mm_hedp_dm21", 35,
					"gm_1rnd_40x46mm_smoke_dm35", 20,
					"gm_1rnd_40x46mm_illum_dm16", 20
				};
			};
			class Flares
			{
				displayname = "Flares";
				realm = "cfgMagazines";

				content[] =
				{
					"gm_1Rnd_265mm_flare_para_yel_DM16",   10,
					"gm_1Rnd_265mm_flare_single_wht_DM15", 10,
					"gm_1Rnd_265mm_flare_single_red_DM13", 10,
					"gm_1Rnd_265mm_flare_single_grn_DM11", 10,
					"gm_1Rnd_265mm_flare_single_yel_DM10", 10,
					"gm_1Rnd_265mm_flare_multi_wht_DM25",  10,
					"gm_1Rnd_265mm_flare_multi_red_DM23",  10,
					"gm_1Rnd_265mm_flare_multi_grn_DM21",  10,
					"gm_1Rnd_265mm_flare_multi_yel_DM20",  10,
					"gm_1Rnd_265mm_smoke_single_yel_DM19", 10,
					"gm_1Rnd_265mm_smoke_single_org_DM22", 10,
					"gm_1Rnd_265mm_smoke_single_vlt_DM24", 10,
					"gm_1Rnd_265mm_flare_multi_nbc_DM47",  10
				};
			};
			class Charges
			{
				displayname = "Charges";
				realm = "cfgMagazines";

				content[] =
				{
					"gm_explosive_petn_charge",   50,

					"gm_mine_ap_dm31", 100,
					"gm_mine_at_dm21", 200
				};
			};
		};
		class Attachments
		{
			displayName = "Attachments";
			class Scopes
			{
				displayname = "Scopes";
				realm = "cfgWeapons";
				content[] =
				{
					"gm_c79a1_blk", 500,
					"gm_c79a1_oli", 500,

					"gm_blits_ris_blk", 1500,
					"gm_blits_stanagClaw_blk", 1500,
					"gm_blits_stanagClaw_oli", 1500,
					"gm_blits_stanagHK_blk", 1500,
					"gm_blits_stanagSig_blk", 1500,

					"gm_colt4x20_ar15_blk", 2500,
					"gm_colt4x20_stanagClaw_blk", 2500,
					"gm_diavari_da_stanagClaw_blk", 5000,
					"gm_diavari_da_stanagClaw_oli", 5000,

					"gm_feroz24_ris_blk", 1000,
					"gm_feroz24_stanagClaw_blk", 1000,
					"gm_feroz24_stanagClaw_oli", 1000,
					"gm_feroz24_stanagHK_blk", 1000,
					"gm_feroz24_stanagSig_blk", 1000,

					"gm_feroz51_pzf44_2_oli", 8000,
					"gm_feroz51_pzf84_oli", 8000,
					"gm_feroz51_ris_oli", 8000,
					"gm_feroz51_stanagClaw_oli", 8000,
					"gm_feroz51_stanagHK_oli", 8000,
					"gm_feroz51_stanagSig_oli", 8000,

					"gm_g11_lps_prism11mm_blk", 5000,
					"gm_g11_mps_prism11mm_blk", 8000,

					"gm_rv_ris_blk", 2500,
					"gm_rv_stanagClaw_blk", 2500,
					"gm_rv_stanagClaw_oli", 2500,
					"gm_rv_stanagHK_blk", 2500,
					"gm_rv_stanagSig_blk", 2500,

					"gm_zf10x42_ris_blk", 4500,
					"gm_zf10x42_ris_oli", 4500,
					"gm_zf10x42_stanagClaw_blk", 4500,
					"gm_zf10x42_stanagClaw_oli", 4500,
					"gm_zf10x42_stanaghk_blk", 4500,
					"gm_zf10x42_stanaghk_oli", 4500,
					"gm_zf10x42_stanagsig_blk", 4500,
					"gm_zf10x42_stanagsig_oli", 4500,

					"gm_zf6x42_psg1_stanag_blk", 3500,

					"gm_zpp_stanagClaw_blk", 1500,

					"gm_feroz2x17_pzf44_2_blk", 250,
					"gm_feroz2x17_pzf84_blk", 250
				};
			};

			class Lights
			{
				displayname = "Lights";
				realm = "cfgWeapons";
				content[] =
				{
					"gm_streamlight_sl20_stanagSig_brn", 500,
					"gm_streamlight_sl20_stanagSig_blk", 500,
					"gm_streamlight_sl20_stanaghk_brn", 500,
					"gm_streamlight_sl20_stanaghk_blk", 500,
					"gm_streamlight_sl20_stanagClaw_brn", 500,
					"gm_streamlight_sl20_stanagClaw_blk", 500,
					"gm_streamlight_sl20_ris_brn", 500,
					"gm_streamlight_sl20_ris_blk", 500,
					"gm_maglite_3d_stanagSig_blk", 500,
					"gm_maglite_3d_stanaghk_blk", 500,
					"gm_maglite_3d_stanagClaw_blk", 500,
					"gm_maglite_3d_ris_blk", 500,
					"gm_maglite_2d_hkslim_blk", 500,
					"gm_surefire_l60_ir_bayonetg11_blk", 500,
					"gm_surefire_l60_ir_hoseclamp_blk", 500,
					"gm_surefire_l60_ir_surefire_blk", 500,
					"gm_surefire_l60_red_bayonetg11_blk", 500,
					"gm_surefire_l60_red_hoseclamp_blk", 500,
					"gm_surefire_l60_red_surefire_blk", 500,
					"gm_surefire_l60_wht_bayonetg11_blk", 500,
					"gm_surefire_l60_wht_hoseclamp_blk", 500,
					"gm_surefire_l60_wht_surefire_blk", 500,

				};
			};

			class Lasers
			{
				displayname = "Lasers";
				realm = "cfgWeapons";
				content[] =
				{
					"gm_lsminiv_red_stanagSig_blk", 11000,
					"gm_lsminiv_red_stanaghk_blk", 11000,
					"gm_lsminiv_red_stanagClaw_blk", 11000,
					"gm_lsminiv_red_ris_blk", 11000,
					"gm_lsminiv_ir_stanagSig_blk", 11000,
					"gm_lsminiv_ir_stanaghk_blk", 11000,
					"gm_lsminiv_ir_stanagClaw_blk", 11000,
					"gm_lsminiv_ir_ris_blk", 11000,
					"gm_ls45_red_uziclaw_blk", 9500,
					"gm_ls45_red_stanagSig_blk", 9500,
					"gm_ls45_red_stanaghk_blk", 9500,
					"gm_ls45_red_stanagClaw_blk", 9500,
					"gm_ls45_red_ris_blk", 9500,
					"gm_ls45_ir_uziclaw_blk", 9500,
					"gm_ls45_ir_stanagSig_blk", 9500,
					"gm_ls45_ir_stanaghk_blk", 9500,
					"gm_ls45_ir_stanagClaw_blk", 9500,
					"gm_ls45_ir_ris_blk", 9500,
					"gm_ls1500_red_stanagSig_blk", 5000,
					"gm_ls1500_red_stanaghk_blk", 5000,
					"gm_ls1500_red_stanagClaw_blk", 5000,
					"gm_ls1500_red_ris_blk", 5000,
					"gm_ls1500_ir_stanagSig_blk", 5000,
					"gm_ls1500_ir_stanaghk_blk", 5000,
					"gm_ls1500_ir_stanagClaw_blk", 5000,
					"gm_ls1500_ir_ris_blk", 5000,
					"gm_surefire_l72_grn_bayonetg11_blk", 15000,
					"gm_surefire_l72_grn_hoseclamp_blk", 15000,
					"gm_surefire_l72_grn_surefire_blk", 15000,
					"gm_surefire_l72_red_bayonetg11_blk", 15000,
					"gm_surefire_l72_red_hoseclamp_blk", 15000,
					"gm_surefire_l72_red_surefire_blk", 15000,
					"gm_surefire_l75_ir_bayonetg11_blk", 15000,
					"gm_surefire_l75_ir_hoseclamp_blk", 15000,
					"gm_surefire_l75_ir_surefire_blk", 15000
				};
			};

			class Silencers
			{
				displayname = "Suppressors";
				realm = "cfgWeapons";
				content[] =
				{
					"gm_suppressor_atec150_556mm_blk", 3500,
					"gm_suppressor_atec150_556mm_long_blk", 3500,
					"gm_suppressor_atec150_762mm_blk", 3500,
					"gm_suppressor_atec150_762mm_long_blk", 3500,
					"gm_suppressor_hknavy_9mm_gry", 3500,
					"gm_suppressor_kacnavy_9mm_blk", 3500,
					"gm_suppressor_kacnavyk_9mm_blk", 3500,
					"gm_suppressor_kacnavysd_9mm_blk", 3500,
					"gm_suppressor_m10_9mm_blk", 3500
				};
			};

			class Bipods
			{
				displayname = "Bipods";
				realm = "cfgWeapons";
				content[] =
				{
					"gm_g3_bipod_blk", 50,
					"gm_g8_bipod_blk", 200,
					"gm_msg90_bipod_blk", 200
				};
			};

			class Bayonets
			{
				displayname = "Bayonets";
				realm = "cfgWeapons";
				content[] =
				{
					"gm_bayonet_g11_blk", 110,
					"gm_bayonet_g11_oli", 110,
					"gm_bayonet_g3_blk", 110,
					"gm_bayonet_g3_oli", 110
				};
			};
		};
		class InfantryEquipment
		{
			displayName = "Personal Equipment";
			class Items
			{
				displayname = "Items";
				realm = "cfgWeapons";
				content[] =
				{
					"itemMap", 10,
					"gm_ge_army_conat2", 10,
					"itemWatch", 10,
					"gm_watch_kosei_80", 20,
					"gm_watch_kosei_80_gold", 2000,
					"gm_watch_kosei_80_slv", 20,
					"gm_watch_kosei_80_blu", 20,
					"gm_watch_kosei_80_red", 20,
					"gm_watch_kosei_80_grn", 20,
					"gm_watch_gub_f455_gm", 20000,
					"gm_ferod16_win", 600,
					"gm_ferod16_oli", 200,
					"gm_ferod51_oli", 60000,
					"gm_lp7_oli", 2000,
					"gm_ge_army_gauzeBandage", 10,
					"gm_ge_army_burnBandage", 10,
					"gm_ge_army_gauzeCompress", 10,
					"gm_ge_army_medkit_80", 100,
					"gm_repairkit_01", 200,
					"gm_boltcutter", 250,

					"ACE_Canteen", 5,
					"ACE_DefusalKit", 5,
					"ACE_EntrenchingTool", 5,
					"ACE_DeadManSwitch", 5,
					"ACE_EarPlugs", 5,
					"ACE_EHP", 5,
					"ACE_DAGR", 5,
					"ACE_M26_Clacker", 5,
					"ACE_Clacker", 5,
					"ACE_MapTools", 5,
					"ACE_Flashlight_XL50", 5,
					"ACE_RangeTable_82mm", 5,
					"ACE_artilleryTable", 5,
					"ACE_PlottingBoard", 5,
					"ACE_RangeCard", 5,
					"ACE_Sandbag_empty", 5,
					"ACE_SpareBarrel", 5
				};
			};
			class Facewear
			{
				displayname = "Facewear";
				realm = "cfgGlasses";
				content[] =
				{
					"gm_ge_facewear_m65", 10,
					"gm_ge_facewear_dustglasses", 10,
					"gm_ge_facewear_dustglasses_relaxed", 10,
					"gm_ge_facewear_sunglasses", 10,
					"gm_ge_facewear_acidgoggles", 120,
					"gm_ge_facewear_stormhood_blk", 50,
					"gm_ge_facewear_stormhood_brd", 50,
					"gm_ge_facewear_stormhood_dustglasses_blk", 150,
					"gm_ge_facewear_glacierglasses", 696969,
					"G_Aviator", 100
				};
			};
			class Scarfs
			{
				displayname = "Scarfs";
				realm = "cfgGlasses";
				content[] =
				{
					"gm_xx_facewear_scarf_01_blk",    200,
					"gm_xx_facewear_scarf_01_blu",    200,
					"gm_xx_facewear_scarf_01_flk",    200,
					// "gm_xx_facewear_scarf_01_frog",200,
					"gm_xx_facewear_scarf_01_grn",    200,
					"gm_xx_facewear_scarf_01_gry",    200,
					"gm_xx_facewear_scarf_01_m84",    200,
					// "gm_xx_facewear_scarf_01_moro",200,
					"gm_xx_facewear_scarf_01_oli",    200,
					"gm_xx_facewear_scarf_01_pt1",    200,
					"gm_xx_facewear_scarf_01_pt2",    200,
					"gm_xx_facewear_scarf_01_pt3",    200,
					"gm_xx_facewear_scarf_01_red",    200,
					// "gm_xx_facewear_scarf_01_str", 200,
					"gm_xx_facewear_scarf_01_trp",    200,
					"gm_xx_facewear_scarf_01_wht",    200,
					"gm_xx_facewear_scarf_02_blk",    200,
					"gm_xx_facewear_scarf_02_grn",    200,
					"gm_xx_facewear_scarf_02_oli",    200,
					"gm_xx_facewear_scarf_02_wht",     200
				};
			};
			class Helmets
			{
				displayname = "Helmets";
				realm = "cfgWeapons";
				content[] =
				{
					"gm_dk_headgear_m52_oli", 100,
					"gm_dk_headgear_m52_net_oli", 100,
					"gm_dk_headgear_m96_blu", 250,
					"gm_dk_headgear_m96_oli", 250,
					"gm_dk_headgear_m96_cover_m84", 250,
					"gm_dk_headgear_m96_cover_wdl", 250,
					"gm_dk_headgear_m96_cover_wht", 250,
					"gm_dk_headgear_m52_net_win", 100,

					"gm_ge_bgs_headgear_m38_72_bgr", 100,
					"gm_ge_bgs_headgear_m38_72_goggles_bgr", 100,

					"gm_ge_headgear_psh77_oli", 200,
					"gm_ge_headgear_psh77_up_oli", 200,
					"gm_ge_headgear_psh77_down_oli", 300,

					"gm_ge_bgs_headgear_psh77_cover_smp", 200,
					"gm_ge_bgs_headgear_psh77_cover_up_smp", 200,
					"gm_ge_bgs_headgear_psh77_cover_down_smp", 300,

					"gm_ge_bgs_headgear_m35_53_blk", 100,
					"gm_ge_ff_headgear_m35_53_tan", 100,
					"gm_ge_bgs_headgear_m35_53_net_blk", 100,

					"gm_ge_headgear_sph4_oli", 100,

					"gm_ge_headgear_m92_flk", 250,
					"gm_ge_headgear_m92_trp", 250,
					"gm_ge_headgear_m92_glasses_trp", 300,
					"gm_ge_headgear_m92_glasses_flk", 300,
					"gm_ge_headgear_m92_cover_win", 250,
					"gm_ge_headgear_m92_cover_glasses_win", 300,

					"gm_ge_headgear_m62", 100,
					"gm_ge_headgear_m62_net", 100,
					"gm_ge_headgear_m62_cover_blu", 100,
					"gm_ge_headgear_m62_cover_wdl", 100,
					"gm_ge_headgear_m62_cover_win", 100,
					"gm_ge_headgear_m62_win_pap_01", 100,
					
					"c23_pasgt_helmet_darkchip", 250,
					"c23_pasgt_helmet_darkchip_chan", 250,
					"c23_pasgt_helm_darkchip_band", 250,
					"c23_pasgt_helm_darkchip_band_nvg", 250,
					"c23_pasgt_helm_darkchip_graffiti_04", 250,
					"c23_pasgt_helmet_darkchip_graffiti_01", 250,
					"c23_pasgt_helmet_darkchip_graffiti_08", 250,
					"c23_pasgt_helmet_darkchip_graffiti_02", 250,
					"c23_pasgt_helmet_darkchip_graffiti_03", 250,
					"c23_pasgt_helmet_darkchip_graffiti_06", 250,
					"c23_pasgt_helmet_darkchip_graffiti_05", 250,
					"c23_pasgt_helmet_darkchip_graffiti_07", 250,
					"c23_pasgt_helmet_darkchip_medic", 250,
					"c23_pasgt_helm_darkchip_scrim", 250,
					"c23_pasgt_helm_darkchip_panama", 250,
					"c23_pasgt_helmet_mosschip", 250,
					"c23_pasgt_helmet_mosschip_chan", 250,
					"c23_pasgt_helm_mosschip_band", 250,
					"c23_pasgt_helm_mosschip_band_nvg", 250,
					"c23_pasgt_helm_mosschip_graffiti_04", 250,
					"c23_pasgt_helmet_mosschip_graffiti_01", 250,
					"c23_pasgt_helmet_mosschip_graffiti_08", 250,
					"c23_pasgt_helmet_mosschip_graffiti_02", 250,
					"c23_pasgt_helmet_mosschip_graffiti_03", 250,
					"c23_pasgt_helmet_mosschip_graffiti_06", 250,
					"c23_pasgt_helmet_mosschip_graffiti_05", 250,
					"c23_pasgt_helmet_mosschip_graffiti_07", 250,
					"c23_pasgt_helmet_mosschip_medic", 250,
					"c23_pasgt_helm_mosschip_scrim", 250,
					"c23_pasgt_helm_mosschip_panama", 250,
					"c23_pasgt_helmet_woodchip", 250,
					"c23_pasgt_helmet_woodchip_chan", 250,
					"c23_pasgt_helm_woodchip_band", 250,
					"c23_pasgt_helm_woodchip_band_nvg", 250,
					"c23_pasgt_helm_woodchip_graffiti_04", 250,
					"c23_pasgt_helmet_woodchip_graffiti_01", 250,
					"c23_pasgt_helmet_woodchip_graffiti_08", 250,
					"c23_pasgt_helmet_woodchip_graffiti_02", 250,
					"c23_pasgt_helmet_woodchip_graffiti_03", 250,
					"c23_pasgt_helmet_woodchip_graffiti_06", 250,
					"c23_pasgt_helmet_woodchip_graffiti_05", 250,
					"c23_pasgt_helmet_woodchip_graffiti_07", 250,
					"c23_pasgt_helmet_woodchip_medic", 250,
					"c23_pasgt_helm_woodchip_scrim", 250,
					"c23_pasgt_helm_woodchip_panama", 250
				};
			};
			class HelmetCamo
			{
				displayname = "Helmets Camo";
				realm = "cfgGlasses";
				content[] =
				{
					"gm_headgear_foliage_summer_grass_01", 5,
					"gm_headgear_foliage_summer_grass_02", 5,
					"gm_headgear_foliage_summer_grass_03", 5,
					"gm_headgear_foliage_summer_grass_04", 5,

					"gm_headgear_foliage_summer_forest_01", 5,
					"gm_headgear_foliage_summer_forest_02", 5,
					"gm_headgear_foliage_summer_forest_03", 5,
					"gm_headgear_foliage_summer_forest_04", 5
				};
			};
			class Headwraps
			{
				displayname = "Headwraps";
				realm = "cfgWeapons";
				content[] =
				{
					"gm_xx_headgear_headwrap_01_blk", 40,
					"gm_xx_headgear_headwrap_01_blu", 40,
					"gm_xx_headgear_headwrap_01_dino",40,
					"gm_xx_headgear_headwrap_01_flk", 40,
					// "gm_xx_headgear_headwrap_01_frog",40,
					"gm_xx_headgear_headwrap_01_grn", 40,
					"gm_xx_headgear_headwrap_01_m84", 40,
					// "gm_xx_headgear_headwrap_01_moro",40,
					"gm_xx_headgear_headwrap_01_oli", 40,
					"gm_xx_headgear_headwrap_01_smp", 40,
					// "gm_xx_headgear_headwrap_01_str", 40,
					"gm_xx_headgear_headwrap_01_trp", 40,
					"gm_xx_headgear_headwrap_01_wht", 40,

					"gm_xx_headgear_headwrap_crew_01_blk", 240,
					"gm_xx_headgear_headwrap_crew_01_flk", 240,
					"gm_xx_headgear_headwrap_crew_01_grn", 240,
					"gm_xx_headgear_headwrap_crew_01_m84", 240,
					"gm_xx_headgear_headwrap_crew_01_oli", 240,
					"gm_xx_headgear_headwrap_crew_01_smp", 240,
					"gm_xx_headgear_headwrap_crew_01_trp", 240
				};
			};
			class Caps
			{
				displayname = "Caps";
				realm = "cfgWeapons";
				content[] =
				{
					"gm_ge_headgear_crewhat_80_blk", 20,
					"gm_ge_headgear_hat_80_gry", 20,
					"gm_ge_headgear_hat_90_flk", 20,
					"gm_ge_headgear_hat_90_trp", 20,
					"gm_ge_headgear_hat_80_m62_oli", 20,
					"gm_ge_headgear_headset_crew_oli", 20,
					"gm_ge_headgear_winterhat_80_oli", 20,

					"gm_ge_headgear_hat_boonie_oli", 20,
					"gm_ge_headgear_hat_boonie_wdl", 20,
					"gm_ge_headgear_hat_boonie_flk", 20,
					"gm_ge_headgear_hat_boonie_trp", 20,

					"gm_ge_headgear_sidecap_80_oli", 20,
					"gm_ge_headgear_sidecap_80_m62_oli", 20,

					"gm_ge_headgear_hat_beanie_blk", 10,
					"gm_ge_headgear_hat_beanie_crew_blk", 120,

					"gm_ge_pol_headgear_cap_80_grn", 50,
					"gm_ge_dbp_headgear_cap_80_blu", 50,
					"gm_ge_pol_headgear_cap_80_wht", 50
				};
			};
			class Berets
			{
				displayname = "Berets";
				realm = "cfgWeapons";
				content[] =
				{
					//berets
					"gm_ge_headgear_beret_bdx",200,
					"gm_ge_headgear_beret_bdx_armyaviation",200,
					"gm_ge_headgear_beret_bdx_lrrp",200,
					"gm_ge_headgear_beret_bdx_paratrooper",200,
					"gm_ge_headgear_beret_bdx_specop",200,
					"gm_ge_headgear_beret_blk",200,
					"gm_ge_headgear_beret_blk_antitank",200,
					"gm_ge_headgear_beret_blk_armor",200,
					"gm_ge_headgear_beret_blk_armorrecon",200,
					"gm_ge_headgear_beret_blk_recon",200,
					"gm_ge_headgear_beret_blu",200,
					"gm_ge_headgear_beret_grn",200,
					"gm_ge_headgear_beret_grn_guardbtl",200,
					"gm_ge_headgear_beret_grn_infantry",200,
					"gm_ge_headgear_beret_grn_mechinf",200,
					"gm_ge_headgear_beret_grn_music",200,
					"gm_ge_bgs_headgear_beret_grn_sf",200,
					"gm_ge_bgs_headgear_beret_grn",200,
					"gm_ge_headgear_beret_mrb",200,
					"gm_ge_headgear_beret_red",200,
					"gm_ge_headgear_beret_red_antiair",200,
					"gm_ge_headgear_beret_red_artillery",200,
					"gm_ge_headgear_beret_red_engineer",200,
					"gm_ge_headgear_beret_red_geoinfo",200,
					"gm_ge_headgear_beret_red_maintenance",200,
					"gm_ge_headgear_beret_red_militarypolice",200,
					"gm_ge_headgear_beret_red_nbc",200,
					"gm_ge_headgear_beret_red_opcom",200,
					"gm_ge_headgear_beret_red_signals",200,
					"gm_ge_headgear_beret_red_supply",200,
					"gm_ge_headgear_beret_un",200,

					"gm_ge_headgear_beret_crew_bdx",200,
					"gm_ge_headgear_beret_crew_bdx_armyaviation",200,
					"gm_ge_headgear_beret_crew_bdx_lrrp",200,
					"gm_ge_headgear_beret_crew_bdx_paratrooper",200,
					"gm_ge_headgear_beret_crew_bdx_specop",200,
					"gm_ge_headgear_beret_crew_blk",200,
					"gm_ge_headgear_beret_crew_blk_antitank",200,
					"gm_ge_headgear_beret_crew_blk_armor",200,
					"gm_ge_headgear_beret_crew_blk_armorrecon",200,
					"gm_ge_headgear_beret_crew_blk_recon",200,
					"gm_ge_headgear_beret_crew_blu",200,
					"gm_ge_headgear_beret_crew_grn",200,
					"gm_ge_headgear_beret_crew_grn_guardbtl",200,
					"gm_ge_headgear_beret_crew_grn_infantry",200,
					"gm_ge_headgear_beret_crew_grn_mechinf",200,
					"gm_ge_headgear_beret_crew_grn_music",200,
					"gm_ge_bgs_headgear_beret_crew_grn_sf",200,
					"gm_ge_bgs_headgear_beret_crew_grn",200,
					"gm_ge_headgear_beret_crew_mrb",200,
					"gm_ge_headgear_beret_crew_red",200,
					"gm_ge_headgear_beret_crew_red_antiair",200,
					"gm_ge_headgear_beret_crew_red_artillery",200,
					"gm_ge_headgear_beret_crew_red_engineer",200,
					"gm_ge_headgear_beret_crew_red_geoinfo",200,
					"gm_ge_headgear_beret_crew_red_maintenance",200,
					"gm_ge_headgear_beret_crew_red_militarypolice",200,
					"gm_ge_headgear_beret_crew_red_nbc",200,
					"gm_ge_headgear_beret_crew_red_opcom",200,
					"gm_ge_headgear_beret_crew_red_signals",200,
					"gm_ge_headgear_beret_crew_red_supply",200,
					"gm_ge_headgear_beret_crew_un",200,
					"c23_beret", 200
				};
			};
			class Vests
			{
				displayname = "Vests";
				realm = "cfgWeapons";
				content[] =
				{
					"gm_dk_army_vest_54_crew",100,
					"gm_dk_army_vest_54_machinegunner",120,
					"gm_dk_army_vest_54_rifleman",100,

					"gm_ge_army_vest_pilot_oli",2000,
					"gm_ge_army_vest_pilot_pads_oli",2000,

					"gm_ge_army_vest_80_bag",100,
					"gm_ge_army_vest_80_belt",100,
					"gm_ge_army_vest_80_crew",100,
					"gm_ge_army_vest_80_demolition",100,
					"gm_ge_army_vest_80_leader",100,
					"gm_ge_army_vest_80_machinegunner",120,
					"gm_ge_army_vest_80_medic",100,
					"gm_ge_army_vest_80_mp_wht",200,
					"gm_ge_army_vest_80_officer",80,
					"gm_ge_army_vest_80_rifleman",100,

					"gm_ge_bgs_vest_80_rifleman",100,
					"gm_ge_pol_vest_80_wht",100,

					"gm_ge_vest_armor_90_flk", 2000,

					"gm_ge_vest_armor_90_crew_flk", 2100,
					"gm_ge_vest_armor_90_leader_flk", 2300,
					"gm_ge_vest_armor_90_machinegunner_flk", 2400,
					"gm_ge_vest_armor_90_officer_flk", 2100,
					"gm_ge_vest_armor_90_rifleman_flk", 2300,
					"gm_ge_vest_armor_90_demolition_flk", 2300,
					"gm_ge_vest_armor_90_medic_flk", 2300,

					"gm_dk_army_vest_m00_m84",2000,
					"gm_dk_army_vest_m00_m84_machinegunner",2400,
					"gm_dk_army_vest_m00_m84_rifleman",2300,

					"gm_dk_army_vest_m00_win",2000,
					"gm_dk_army_vest_m00_win_machinegunner",2400,
					"gm_dk_army_vest_m00_win_rifleman",2300,

					"gm_dk_army_vest_m00_wdl",2000,
					"gm_dk_army_vest_m00_wdl_rifleman",2300,

					"gm_dk_army_vest_m00_blu",2000,

					"gm_ge_army_vest_type18_dpm",4000,
					"gm_ge_bgs_vest_type18_blk",4000,
					"gm_ge_bgs_vest_type18_grn",4000,

					"gm_ge_bgs_vest_type3_gry",2000,
					"gm_ge_bgs_vest_type3_oli",2000,
					"gm_ge_bgs_vest_type3_blu",2000,

					"gm_ge_bgs_vest_type3a1_gry",3000,
					"gm_ge_bgs_vest_type3a1_oli",3000,

					"gm_ge_vest_sov_80_blk",1500,
					"gm_ge_vest_sov_80_oli",1500,
					"gm_ge_vest_sov_80_wdl",1500,

					"gm_ge_vest_sov_armor_80_blk",4500,
					"gm_ge_vest_sov_armor_80_oli",4500,
					"gm_ge_vest_sov_armor_80_wdl",4500,

					"gm_ge_vest_90_crew_flk", 100,
					"gm_ge_vest_90_demolition_flk", 100,
					"gm_ge_vest_90_leader_flk", 100,
					"gm_ge_vest_90_machinegunner_flk", 120,
					"gm_ge_vest_90_medic_flk", 100,
					"gm_ge_vest_90_officer_flk", 100,
					"gm_ge_vest_90_rifleman_flk", 100,
					
					"c23_vest_pasgt_od", 3000,
					"c23_pasgt_vest_od_lbv1", 3000,
					"c23_pasgt_vest_od_lbv2", 3000,
					"c23_pasgt_vest_od_alice_alt", 3000,
					"c23_pasgt_vest_od_alice", 3000,
					"c23_pasgt_vest_od_alice_etool", 3000,
					"c23_pasgt_vest_od_alice_45", 3000,
					"c23_pasgt_vest_od_alice_60", 3000,
					"c23_pasgt_vest_od_alice_249", 3000,
					"c23_vest_pasgt_darkchip", 3000,
					"c23_pasgt_vest_darkchip_lbv1", 3000,
					"c23_pasgt_vest_darkchip_lbv2", 3000,
					"c23_pasgt_vest_darkchip_alice", 3000,
					"c23_pasgt_vest_darkchip_alice_alt", 3000,
					"c23_pasgt_vest_darkchip_alice_etool", 3000,
					"c23_pasgt_vest_darkchip_alice_45", 3000,
					"c23_pasgt_vest_darkchip_alice_60", 3000,
					"c23_pasgt_vest_darkchip_alice_249", 3000,
					"c23_vest_pasgt_mosschip", 3000,
					"c23_pasgt_vest_mosschip_lbv1", 3000,
					"c23_pasgt_vest_mosschip_lbv2", 3000,
					"c23_pasgt_vest_mosschip_alice", 3000,
					"c23_pasgt_vest_mosschip_alice_alt", 3000,
					"c23_pasgt_vest_mosschip_alice_etool", 3000,
					"c23_pasgt_vest_mosschip_alice_45", 3000,
					"c23_pasgt_vest_mosschip_alice_60", 3000,
					"c23_pasgt_vest_mosschip_alice_249", 3000,
					"c23_vest_pasgt_woodchip", 3000,
					"c23_pasgt_vest_woodchip_lbv1", 3000,
					"c23_pasgt_vest_woodchip_lbv2", 3000,
					"c23_pasgt_vest_woodchip_alice", 3000,
					"c23_pasgt_vest_woodchip_alice_alt", 3000,
					"c23_pasgt_vest_woodchip_alice_etool", 3000,
					"c23_pasgt_vest_woodchip_alice_45", 3000,
					"c23_pasgt_vest_woodchip_alice_60", 3000,
					"c23_pasgt_vest_woodchip_alice_249", 3000
				};
			};
			class Uniforms
			{
				displayname = "Uniforms";
				realm = "cfgWeapons";
				content[] =
				{
					"gm_ge_army_uniform_soldier_80_ols", 100,
					"gm_ge_army_uniform_soldier_gloves_80_ols", 100,
					"gm_ge_army_uniform_soldier_parka_80_ols", 100,
					"gm_ge_army_uniform_soldier_parka_80_win", 100,
					"gm_ge_army_uniform_crew_80_oli", 100,

					"gm_dk_army_uniform_soldier_84_m84", 100,
					"gm_dk_army_uniform_soldier_84_oli", 100,
					"gm_dk_army_uniform_soldier_84_win", 100,

					"gm_ge_uniform_soldier_rolled_90_flk", 100,
					"gm_ge_uniform_soldier_rolled_90_trp", 100,
					"gm_ge_uniform_soldier_90_flk", 100,
					"gm_ge_uniform_soldier_90_trp", 100,
					"gm_ge_uniform_soldier_tshirt_90_flk", 100,
					"gm_ge_uniform_soldier_tshirt_90_trp", 100,
					"gm_ge_uniform_soldier_tshirt_90_oli", 100,
					"gm_ge_army_uniform_crew_90_flk", 100,

					"gm_ge_bgs_uniform_soldier_80_smp", 100,

					"gm_ge_bgs_uniform_special_80_blk", 100,
					"gm_ge_bgs_uniform_special_80_grn", 100,
					"gm_ge_bgs_uniform_special_rolled_80_blk", 100,
					"gm_ge_bgs_uniform_special_rolled_80_grn", 100,

					"gm_xx_uniform_soldier_bdu_80_wdl", 100,
					"gm_xx_uniform_soldier_bdu_80_oli", 100,
					"gm_xx_uniform_soldier_bdu_rolled_80_wdl", 100,
					"gm_xx_uniform_soldier_bdu_rolled_80_oli", 100,

					"gm_ge_army_uniform_pilot_oli", 100,
					"gm_ge_pol_uniform_pilot_grn", 100,
					"gm_ge_army_uniform_pilot_sar", 100,

					"gm_ge_army_uniform_pilot_rolled_oli", 100,
					"gm_ge_pol_uniform_pilot_rolled_grn", 100,
					"gm_ge_army_uniform_pilot_rolled_sar", 100,

					"gm_ge_uniform_pilot_commando_oli", 100,
					"gm_ge_uniform_pilot_commando_blk", 100,
					"gm_ge_uniform_pilot_commando_gry", 100,

					"gm_ge_uniform_pilot_commando_rolled_oli", 100,
					"gm_ge_uniform_pilot_commando_rolled_blk", 100,
					"gm_ge_uniform_pilot_commando_rolled_gry", 100,

					"gm_ge_ff_uniform_man_80_orn", 100,
					"gm_ge_pol_uniform_suit_80_grn", 100,
					"gm_ge_dbp_uniform_suit_80_blu", 100,
					
					"c23_uniform_tshirt_woodchip_ace", 100,
					"c23_uniform_tshirt_woodchip_baes", 100,
					"c23_uniform_tshirt_woodchip_brown", 100,
					"c23_uniform_tshirt_woodchip_fish", 100,
					"c23_uniform_tshirt_woodchip_glow", 100,
					"c23_uniform_tshirt_woodchip_green", 100,
					"c23_uniform_tshirt_woodchip_satire", 100,
					"c23_uniform_tshirt_woodchip_stripe", 100,
					"c23_uniform_bdu_woodchip", 100,
					"c23_uniform_bdu_woodchip_rolled_low", 100,
					"c23_uniform_bdu_woodchip_rolled", 100,
					"c23_uniform_bdu_woodchip_mixed", 100,
					"c23_uniform_bdu_woodchip_mixed_rolled", 100,
					"c23_uniform_bdu_woodchip_mixed_rolled_low", 100,
					"c23_uniform_sweater_woodchip_black", 100,
					"c23_uniform_sweater_woodchip_green", 100,
					"c23_uniform_bdu_dnce_dnc_over_woodchip", 100,
					"c23_uniform_sweater_woodchip_purple", 100,
					"c23_uniform_tshirt_mosschip_ace", 100,
					"c23_uniform_tshirt_mosschip_baes", 100,
					"c23_uniform_tshirt_mosschip_brown", 100,
					"c23_uniform_tshirt_mosschip_fish", 100,
					"c23_uniform_tshirt_mosschip_glow", 100,
					"c23_uniform_tshirt_mosschip_green", 100,
					"c23_uniform_tshirt_mosschip_satire", 100,
					"c23_uniform_tshirt_mosschip_stripe", 100,
					"c23_uniform_bdu_mosschip", 100,
					"c23_uniform_bdu_mosschip_rolled_low", 100,
					"c23_uniform_bdu_mosschip_rolled", 100,
					"c23_uniform_bdu_mosschip_mixed", 100,
					"c23_uniform_bdu_mosschip_mixed_rolled", 100,
					"c23_uniform_bdu_mosschip_mixed_rolled_low", 100,
					"c23_uniform_sweater_mosschip_black", 100,
					"c23_uniform_sweater_mosschip_green", 100,
					"c23_uniform_bdu_dnce_dnc_over_mosschip", 100,
					"c23_uniform_sweater_mosschip_purple", 100,
					"c23_uniform_bdu_darkchip", 100,
					"c23_uniform_bdu_darkchip_rolled_low", 100,
					"c23_uniform_bdu_darkchip_rolled", 100,
					"c23_uniform_bdu_darkchip_mixed", 100,
					"c23_uniform_bdu_darkchip_mixed_rolled", 100,
					"c23_uniform_bdu_darkchip_mixed_rolled_low", 100,
					"c23_uniform_sweater_darkchip_black", 100,
					"c23_uniform_sweater_darkchip_green", 100,
					"c23_uniform_bdu_dnce_dnc_over_darkchip", 100,
					"c23_uniform_sweater_darkchip_purple", 100,
					"c23_uniform_crewman_black", 100,
					"c23_uniform_crewman_mosschip", 100,
					"c23_uniform_crewman_od", 100,
					"c23_uniform_crewman_purple", 100,
					"c23_uniform_crewman_tan", 100,
					"c23_uniform_crewman_woodchip", 100,
					"c23_uniform_tshirt_darkchip_ace", 100,
					"c23_uniform_tshirt_darkchip_baes", 100,
					"c23_uniform_tshirt_darkchip_brown", 100,
					"c23_uniform_tshirt_darkchip_fish", 100,
					"c23_uniform_tshirt_darkchip_glow", 100,
					"c23_uniform_tshirt_darkchip_green", 100,
					"c23_uniform_tshirt_darkchip_satire", 100,
					"c23_uniform_tshirt_darkchip_stripe", 100
				};
			};
			class Backpacks
			{
				displayname = "Backpacks";
				realm = "cfgVehicles";
				content[] =
				{
					"gm_ge_army_backpack_80_oli", 300,
					"gm_ge_backpack_satchel_80_blk", 300,
					"gm_ge_backpack_satchel_80_san", 300,
					"gm_dk_army_backpack_73_oli", 300,
					"gm_milan_launcher_weaponBag", 3500,
					"gm_mg3_aatripod_weaponBag", 200,

					"gm_ge_backpack_sem35_oli", 200,

					"gm_ge_army_backpack_90_flk", 400,
					"gm_ge_army_backpack_90_trp", 400,
					"gm_ge_army_backpack_90_oli", 400,
					"gm_ge_army_backpack_90_blk", 400,
					"gm_ge_army_backpack_90_cover_win", 400,

					"gm_backpack_t10_parachute", 100
				};
			};
		};
		class Vehicles
		{
			displayName = "Vehicles";
			class Biwheels
			{
				displayname = "Biwheels";
				realm = "cfgVehicles";
				content[] =
				{
					"gm_ge_army_k125", 300
				};
			};

			class Cars
			{
				displayname = "Cars";
				realm = "cfgVehicles";
				content[] =
				{
					"gm_ge_army_typ1200_cargo_oli", 400,
					"gm_ge_army_typ247_firefighter", 1500,
					"gm_ge_army_typ247_cargo", 1200,
					"gm_ge_army_typ253_cargo", 600,
					"gm_ge_army_typ253_mp", 600,
					"gm_ge_army_iltis_cargo_oli", 600,
					"gm_ge_army_iltis_mg3_oli", 1600,
					"gm_ge_army_iltis_milan_oli", 4000,
					"gm_ge_army_w123_cargo", 100000
				};
			};

			class Trucks
			{
				displayname = "Trucks";
				realm = "cfgVehicles";
				content[] =
				{
					"gm_ge_army_kat1_451_cargo_oli", 2000,
					"gm_ge_army_kat1_451_container_oli", 2000,
					"gm_ge_army_kat1_452_container_oli", 2000,
					"gm_ge_army_kat1_454_cargo_oli", 2500,

					"gm_ge_army_u1300l_cargo_oli", 1500,
					"gm_ge_army_u1300l_container_oli", 1500,
					"gm_ge_army_u1300l_firefighter_oli", 1500
				};
			};

			class Supply
			{
				restricted = 1;
				displayname = "Supply";
				realm = "cfgVehicles";
				content[] =
				{
					"gm_ge_army_kat1_451_refuel_oli", 5000,
					"gm_ge_army_kat1_451_reammo_oli", 10000,
					"gm_ge_army_kat1_454_reammo_oli", 11000,

					"gm_ge_army_u1300l_repair_oli", 5000,
					"gm_ge_army_u1300l_medic", 5000,

					"gm_ge_army_shelteraceII_medic", 2500,
					"gm_ge_army_shelteraceII_repair", 2500,
					"gm_ge_army_shelteraceII_reammo", 5500
				};
			};

			class MHQs
			{
				displayname = "Mobile Spawn Points";
				realm = "cfgVehicles";
				content[] =
				{
					"gm_ge_army_fuchsa0_command_oli", 16000,
					"gm_ge_army_m113a1g_command_oli", 16000,
					"gm_dk_army_m113a1dk_command_wdl", 16000,

					"gm_ge_army_shelteraceI_command_oli", 4000
				};
			};

			class APC
			{
				displayname = "APC";
				realm = "cfgVehicles";
				content[] =
				{
					"gm_ge_army_fuchsa0_reconnaissance_oli", 5000,
					"gm_ge_army_fuchsa0_medic", 5000,
					"gm_ge_army_fuchsa0_engineer_oli", 5500,
					"gm_ge_army_fuchsa1_jammer_oli", 5000,

					"gm_ge_army_m113a1g_apc_oli", 4500,
					"gm_ge_army_m113a1g_apc_milan_oli", 6000,
					"gm_ge_army_m113a1g_medic_oli_rc", 5000,

					"gm_ge_army_marder1a1plus", 10000,
					"gm_ge_army_marder1a1a", 11000,
					"gm_ge_army_marder1a2", 12000,

					"gm_dk_army_m113a1dk_apc_wdl", 5000,
					"gm_dk_army_m113a1dk_engineer_wdl", 5000,
					"gm_dk_army_m113a1dk_medic", 5000,

					"gm_dk_army_m113a2dk_wdl", 12000
				};
			};

			class AA
			{
				displayname = "AAA";
				realm = "cfgVehicles";
				content[] =
				{
					"gm_ge_army_gepard1a1_oli", 15000
				};
			};

			class Armor
			{
				displayname = "Tanks";
				realm = "cfgVehicles";
				content[] =
				{
					"gm_ge_army_rakjpz2_oli", 15000,

					"gm_ge_army_leopard1a1_oli",  19000,
					"gm_ge_army_Leopard1a1a1_oli",  20000,
					"gm_ge_army_Leopard1a1a2_oli",  22000,

					"gm_ge_army_Leopard1a3_oli",    22000,
					"gm_ge_army_Leopard1a3a1_oli",  22500,

					"gm_ge_army_Leopard1a4_oli",   29000,

					"gm_ge_army_Leopard1a5_oli",   30000,

					"gm_ge_army_luchsa1_oli", 15000,
					"gm_ge_army_luchsa2_wdl", 18000,

					"gm_dk_army_leopard1a3_wdl", 22000,
					"gm_dk_army_Leopard1a5dk1",   32000,
					"gm_dk_army_Leopard1a5dk1_dozer",   33000
				};
			};

			class Artillery
			{
				displayname = "Artillery";
				realm = "cfgVehicles";
				content[] =
				{
					"gm_ge_army_kat1_463_mlrs_wdl", 85000,
					"gm_ge_army_m109g_oli", 55000,
					"gm_dk_army_m109_wdl", 55000,
					"gm_ge_army_m113a1g_mortar_oli", 32000,
					"gm_ge_army_m120", 20000
				};
			};

			class Engineering
			{
				displayname = "Engineering";
				realm = "cfgVehicles";
				content[] =
				{
					"gm_ge_army_bpz2a0_oli", 8000,
					"gm_ge_army_bibera0", 10000,
					"gm_dk_army_bibera0", 10000
				};
			};

			class Helicopters
			{
				displayname = "Helicopters";
				realm = "cfgVehicles";
				content[] =
				{
					"gm_ge_army_ch53g_n83", 17000,
					"gm_ge_army_ch53gs_n83", 21000,

					"gm_ge_army_bo105p_pah1_n83", 23000,
					"gm_ge_army_bo105p_pah1a1_n83", 28000,

					"gm_ge_army_bo105m_vbh_n83", 14000,
					"gm_ge_army_bo105p1m_vbh_n83", 15000,
					"gm_ge_army_bo105p1m_vbh_swooper_n83", 15000
				};
			};

			class Planes
			{
				displayname = "Planes";
				realm = "cfgVehicles";
				content[] =
				{
					"gm_ge_airforce_do28d2_n83", 12000,
					"gm_ge_airforce_do28d2_medevac_n83", 10000
				};
			};
		};
	};
	class PACT
	{
		class SmallArms
		{
			displayName = "Small Arms";
			class Weapons
			{
				displayname = "Weapons";
				realm = "cfgWeapons";
				content[] =
				{
					"gm_akmn_wud", 650,
					"gm_akml_wud", 650,
					"gm_akmn_wud", 650,
					"gm_akms_wud", 650,
					"gm_akmsl_wud", 650,
					"gm_akmsn_wud", 650,
					"gm_akm_pallad_wud", 800,
					"gm_mpikm_brn", 650,
					"gm_mpikm72_prp", 650,
					"gm_mpikm72_brn", 650,
					"gm_mpikm72_blk", 650,
					"gm_mpikms72_brn", 650,
					"gm_mpikms72_prp", 650,
					"gm_mpikms72_blk", 650,
					"gm_mpikms72k_brn", 650,
					"gm_mpikms72k_prp", 650,
					"gm_mpikms72k_blk", 650,
					"gm_mpikms72ksd_brn", 1650,
					"gm_mpikms72ksd_prp", 1650,
					"gm_mpikms72ksd_blk", 1650,
					"gm_rpk_wud", 900,
					"gm_lmgrpk_prp", 900,
					"gm_lmgrpk_brn", 900,

					"gm_mpiak74n_prp",   650,
					"gm_mpiak74n_brn",   650,
					"gm_mpiak74n_blk",   650,
					"gm_mpiaks74n_prp",  650,
					"gm_mpiaks74n_brn",  650,
					"gm_mpiaks74n_blk",  650,
					"gm_mpiaks74nk_prp", 650,
					"gm_mpiaks74nk_brn", 650,
					"gm_mpiaks74nk_blk", 650,
					"gm_lmgrpk74n_prp",  750,
					"gm_lmgrpk74n_brn",   750,
					"gm_lmgrpk74n_blk",   750,
					"gm_lmgk500_blk",   750,
					"gm_lmgk500_brn",   750,
					"gm_lmgk500_prp",   750,
					"gm_lmgk500s_blk",   750,
					"gm_lmgk500s_brn",   750,
					"gm_lmgk500s_prp",   750,

					"gm_svd_wud", 1200,

					"gm_hmgpkm_prp", 1400,

					"gm_pm63_blk", 400,

					"gm_lp1_blk", 125,
					"gm_wz78_blk", 125,
					"gm_pm_blk", 100
				};
			};
			class Handguns
			{
				displayname = "Handguns";
				realm = "cfgWeapons";
				content[] =
				{
					"gm_pm63_handgun_blk", 400,

					"gm_lp1_blk", 125,
					"gm_wz78_blk", 125,
					"gm_pm_blk", 100,
					"gm_pim_blk", 100,
					"gm_pimb_blk", 120
				};
			};
			class Magazines
			{
				displayname = "Magazines";
				realm = "cfgMagazines";
				content[] =
				{
					"gm_30Rnd_545x39mm_b_7N6_ak74_org",60,
					"gm_30Rnd_545x39mm_b_t_7T3_ak74_org",60,
					"gm_45Rnd_545x39mm_b_7N6_ak74_org",70,
					"gm_45Rnd_545x39mm_b_t_7T3_ak74_org",70,
					"gm_30Rnd_545x39mm_b_7N6_ak74_prp",60,
					"gm_30Rnd_545x39mm_b_t_7T3_ak74_prp",60,
					"gm_45Rnd_545x39mm_b_7N6_ak74_prp",70,
					"gm_45Rnd_545x39mm_b_t_7T3_ak74_prp",70,
					"gm_30Rnd_545x39mm_b_7N6_ak74_blk",60,
					"gm_30Rnd_545x39mm_b_t_7T3_ak74_blk",60,
					"gm_45Rnd_545x39mm_b_7N6_ak74_blk",70,
					"gm_45Rnd_545x39mm_b_t_7T3_ak74_blk",70,

					"gm_30Rnd_762x39mm_b_57N231_ak47_blk",60,
					"gm_30Rnd_762x39mm_bsd_57N231U_ak47_blk",60,
					"gm_30Rnd_762x39mm_b_t_57N231P_ak47_blk",60,
					"gm_30Rnd_762x39mm_ap_7N23_ak47_blk",120,
					"gm_30Rnd_762x39mm_b_M43_ak47_blk",40,
					"gm_30Rnd_762x39mm_b_t_M43_ak47_blk",40,
					"gm_30Rnd_762x39mm_b_57N231_mpikm_blk",60,
					"gm_30Rnd_762x39mm_bsd_57N231U_mpikm_blk",60,
					"gm_30Rnd_762x39mm_b_t_57N231P_mpikm_blk",60,
					"gm_30Rnd_762x39mm_ap_7N23_mpikm_blk",120,
					"gm_30Rnd_762x39mm_b_57N231_akm_blk",60,
					"gm_30Rnd_762x39mm_bsd_57N231U_akm_blk",60,
					"gm_30Rnd_762x39mm_b_t_57N231P_akm_blk",60,
					"gm_30Rnd_762x39mm_ap_7N23_akm_blk",120,
					"gm_30Rnd_762x39mm_b_57N231_akm_org",60,
					"gm_30Rnd_762x39mm_bsd_57N231U_akm_org",60,
					"gm_30Rnd_762x39mm_b_t_57N231P_akm_org",60,
					"gm_30Rnd_762x39mm_ap_7N23_akm_org",120,
					"gm_75Rnd_762x39mm_b_57N231_ak47_blk",90,
					"gm_75Rnd_762x39mm_bsd_57N231U_ak47_blk",90,
					"gm_75Rnd_762x39mm_b_t_57N231P_ak47_blk",90,
					"gm_75Rnd_762x39mm_ap_7N23_ak47_blk",180,
					"gm_75Rnd_762x39mm_b_M43_ak47_blk",70,
					"gm_75Rnd_762x39mm_b_t_M43_ak47_blk",70,
					"gm_75Rnd_762x39mm_b_57N231_mpikm_blk",90,
					"gm_75Rnd_762x39mm_bsd_57N231U_mpikm_blk",90,

					"gm_10Rnd_762x54mmR_b_t_7t2_svd_blk", 70,
					"gm_10Rnd_762x54mmR_ap_7n1_svd_blk", 140,
					"gm_10Rnd_762x54mmR_api_7bz3_svd_blk", 200,

					"gm_15Rnd_9x18mm_b_pst_pm63_blk", 15,
					"gm_25Rnd_9x18mm_b_pst_pm63_blk", 25,

					"gm_100Rnd_762x54mmR_b_t_7t2_pk_grn",    200,
					"gm_100Rnd_762x54mmR_api_7bz3_pk_grn",    400,

					"gm_8rnd_9x18mm_b_pst_pm_blk",          10
				};
			};
			class Launchers
			{
				displayname = "Launchers";
				realm = "cfgWeapons";
				content[] =
				{
					"gm_rpg18_oli", 120,
					"gm_rpg7_wud", 400,
					"gm_9k32m_oli", 600,
					"gm_pallad_d_brn", 200
				};
			};
			class Grenades
			{
				displayname = "Grenades/Rockets";
				realm = "cfgMagazines";

				content[] =
				{
					"gm_1Rnd_64mm_heat_pg18",   80,

					"gm_1Rnd_40mm_heat_pg7v_rpg7",   80,
					"gm_1Rnd_40mm_heat_pg7vl_rpg7",   180,
					"gm_1Rnd_72mm_he_9m32m",   100,

					"gm_handgrenade_frag_rgd5",  20,

					"gm_smokeshell_grn_gc",  20,
					"gm_smokeshell_blk_gc",  20,
					"gm_smokeshell_red_gc",  20,
					"gm_smokeshell_yel_gc",  20,
					"gm_smokeshell_blu_gc",  20,
					"gm_smokeshell_org_gc",  20,
					"gm_smokeshell_wht_gc",  20,

					"gm_1rnd_40x47mm_he_ngo74", 30
				};
			};
			class Flares
			{
				displayname = "Flares";
				realm = "cfgMagazines";

				content[] =
				{
					"gm_1Rnd_265mm_flare_single_wht_gc", 10,
					"gm_1Rnd_265mm_flare_single_grn_gc", 10,
					"gm_1Rnd_265mm_flare_single_red_gc", 10,
					"gm_1Rnd_265mm_flare_multi_red_gc",  10,
					"gm_1Rnd_265mm_smoke_single_yel_gc", 10,
					"gm_1Rnd_265mm_smoke_single_blu_gc", 10,
					"gm_1Rnd_265mm_smoke_single_blk_gc", 10
				};
			};
			class Charges
			{
				displayname = "Charges";
				realm = "cfgMagazines";

				content[] =
				{
					"gm_explosive_plnp_charge",   50,

					"gm_mine_at_tm46", 200
				};
			};
		};
		class Attachments
		{
			displayName = "Attachments";
			class Scopes
			{
				displayname = "Scopes";
				realm = "cfgWeapons";
				content[] =
				{
					"gm_nspu_dovetail_blk", 8000,
					"gm_nspu_dovetail_gry", 8000,
					"gm_pgo7v_blk", 250,
					"gm_pka_dovetail_blk", 2500,
					"gm_pka_dovetail_gry", 2500,
					"gm_pso1_dovetail_blk", 1000,
					"gm_pso1_dovetail_gry", 1000,
					"gm_pso6x36_1_dovetail_blk", 3500,
					"gm_pso6x36_1_dovetail_gry", 3500,
					"gm_zfk4x25_blk", 2500,

					"gm_zvn64_ak", 50,
					"gm_zvn64_akk", 50,
					"gm_zvn64_lmgk500", 50,
					"gm_zvn64_rpk", 50
				};
			};

			class Lights
			{
				displayname = "Lights";
				realm = "cfgWeapons";
				content[] =
				{
					"gm_flashlightp2_wht_ak74handguard_blu", 500,
					"gm_flashlightp2_wht_akhandguard_blu", 500,
					"gm_flashlightp2_wht_akkhandguard_blu", 500,

					"gm_flashlightp2_brk_ak74handguard_dino", 3500,
					"gm_flashlightp2_brk_akhandguard_dino", 3500,
					"gm_flashlightp2_brk_akkhandguard_dino", 3500
				};
			};

			class Lasers
			{
				displayname = "Lasers";
				realm = "cfgWeapons";
				content[] =
				{
					"gm_zln1k_grn_dovetail_blk", 1200,
					"gm_zln1k_grn_dovetail_gry", 1200,
					"gm_zln1k_ir_dovetail_blk", 1200,
					"gm_zln1k_ir_dovetail_gry", 1200
				};
			};

			class Silencers
			{
				displayname = "Suppressors";
				realm = "cfgWeapons";
				content[] =
				{
					"gm_suppressor_pbs1_762mm_blk", 3500,
					"gm_suppressor_safloryt_blk", 3500,
					"gm_suppressor_pbs4_545mm_blk", 3500,
					"gm_suppressor_tgpp_9mm_blk", 3500,
					"gm_suppressor_tgpv_762mm_blk", 3500
				};
			};

			class Bayonets
			{
				displayname = "Bayonets";
				realm = "cfgWeapons";
				content[] =
				{
					"gm_bayonet_6x3_blk", 110,
					"gm_bayonet_6x3_wud", 110
				};
			};
		};
		class InfantryEquipment
		{
			displayName = "Personal Equipment";
			class Items
			{
				displayname = "Items";
				realm = "cfgWeapons";
				content[] =
				{
					"itemMap", 10,
					"gm_gc_compass_f73", 10,
					"itemWatch", 10,
					"gm_watch_kosei_80", 20,
					"gm_watch_kosei_80_gold", 2000,
					"gm_watch_kosei_80_slv", 20,
					"gm_watch_kosei_80_blu", 20,
					"gm_watch_kosei_80_red", 20,
					"gm_watch_kosei_80_grn", 20,
					"gm_watch_gub_f455_gm", 20000,
					"gm_df7x40_blk", 200,
					"gm_df7x40_grn", 200,
					"gm_nsg66_oli", 60000,
					"gm_pn3_gry", 200,
					"gm_lpr1_oli", 2000,
					"gm_gc_army_gauzeBandage", 10,
					"gm_gc_army_medkit", 10,
					"gm_gc_army_medbox", 100,
					"gm_repairkit_01", 200,
					"gm_boltcutter", 250
				};
			};
			class Facewear
			{
				displayname = "Facewear";
				realm = "cfgGlasses";
				content[] =
				{
					"gm_gc_army_facewear_dustglasses", 10,
					"gm_gc_army_facewear_schm41m", 10,
					"gm_ge_facewear_stormhood_blk", 50,
					"gm_ge_facewear_stormhood_brd", 50,
					"gm_ge_facewear_glacierglasses", 696969,
					"G_Aviator", 100
				};
			};
			class Scarfs
			{
				displayname = "Scarfs";
				realm = "cfgGlasses";
				content[] =
				{
					"gm_xx_facewear_scarf_01_blk",    200,
					"gm_xx_facewear_scarf_01_blu",    200,
					// "gm_xx_facewear_scarf_01_flk",    200,
					"gm_xx_facewear_scarf_01_frog",200,
					"gm_xx_facewear_scarf_01_grn",    200,
					"gm_xx_facewear_scarf_01_gry",    200,
					// "gm_xx_facewear_scarf_01_m84",    200,
					"gm_xx_facewear_scarf_01_moro",200,
					"gm_xx_facewear_scarf_01_oli",    200,
					"gm_xx_facewear_scarf_01_pt1",    200,
					"gm_xx_facewear_scarf_01_pt2",    200,
					"gm_xx_facewear_scarf_01_pt3",    200,
					"gm_xx_facewear_scarf_01_red",    200,
					"gm_xx_facewear_scarf_01_str", 200,
					// "gm_xx_facewear_scarf_01_trp",    200,
					"gm_xx_facewear_scarf_01_wht",    200,
					"gm_xx_facewear_scarf_02_blk",    200,
					"gm_xx_facewear_scarf_02_grn",    200,
					"gm_xx_facewear_scarf_02_oli",    200,
					"gm_xx_facewear_scarf_02_wht",     200
				};
			};
			class Helmets
			{
				displayname = "Helmets";
				realm = "cfgWeapons";
				content[] =
				{
					"gm_gc_army_headgear_m56", 100,
					"gm_gc_army_headgear_m56_net", 100,
					"gm_gc_army_headgear_m56_cover_str", 100,
					"gm_gc_army_headgear_m56_cover_blu", 100,
					"gm_gc_army_headgear_m56_cover_win", 100,

					"gm_gc_army_headgear_m86", 100,
					"gm_gc_army_headgear_m86_net", 100,
					"gm_gc_army_headgear_m86_cover_str", 100,
					"gm_gc_army_headgear_m86_cover_blu", 100,
					"gm_gc_army_headgear_m86_cover_win", 100,

					"gm_pl_headgear_wz67_oli", 100,
					"gm_pl_army_headgear_wz67_oli", 100,
					"gm_pl_army_headgear_wz67_net_oli", 100,
					"gm_pl_headgear_wz67_cover_win", 100,

					"gm_gc_headgear_zsh3_orn", 100,
					"gm_gc_headgear_zsh3_wht", 100,
					"gm_gc_headgear_zsh3_blu", 100,

					"gm_ge_headgear_psh77_oli", 200,
					"gm_ge_headgear_psh77_up_oli", 200,
					"gm_ge_headgear_psh77_down_oli", 300,

					"gm_ge_bgs_headgear_psh77_cover_str", 200,
					"gm_ge_bgs_headgear_psh77_cover_up_str", 200,
					"gm_ge_bgs_headgear_psh77_cover_down_str", 300,

					"gm_gc_headgear_fjh_model4_oli", 100,
					"gm_gc_headgear_fjh_model4_wht", 100,

					"gm_pl_army_headgear_wz63_oli", 100,
					"gm_pl_army_headgear_wz63_net_oli", 100
				};
			};
			class HelmetCamo
			{
				displayname = "Helmets Camo";
				realm = "cfgGlasses";
				content[] =
				{
					"gm_headgear_foliage_summer_grass_01", 5,
					"gm_headgear_foliage_summer_grass_02", 5,
					"gm_headgear_foliage_summer_grass_03", 5,
					"gm_headgear_foliage_summer_grass_04", 5,

					"gm_headgear_foliage_summer_forest_01", 5,
					"gm_headgear_foliage_summer_forest_02", 5,
					"gm_headgear_foliage_summer_forest_03", 5,
					"gm_headgear_foliage_summer_forest_04", 5
				};
			};
			class Headwraps
			{
				displayname = "Headwraps";
				realm = "cfgWeapons";
				content[] =
				{
					"gm_xx_headgear_headwrap_01_blk", 40,
					"gm_xx_headgear_headwrap_01_blu", 40,
					"gm_xx_headgear_headwrap_01_dino",40,
					// "gm_xx_headgear_headwrap_01_flk", 40,
					"gm_xx_headgear_headwrap_01_frog",40,
					"gm_xx_headgear_headwrap_01_grn", 40,
					// "gm_xx_headgear_headwrap_01_m84", 40,
					"gm_xx_headgear_headwrap_01_moro",40,
					"gm_xx_headgear_headwrap_01_oli", 40,
					// "gm_xx_headgear_headwrap_01_smp", 40,
					"gm_xx_headgear_headwrap_01_str", 40,
					// "gm_xx_headgear_headwrap_01_trp", 40,
					"gm_xx_headgear_headwrap_01_wht", 40
				};
			};
			class Caps
			{
				displayname = "Caps";
				realm = "cfgWeapons";
				content[] =
				{
					"gm_gc_army_headgear_crewhat_80_blk", 20,
					"gm_gc_army_headgear_cap_80_gry", 20,
					"gm_gc_pol_headgear_cap_80_blu", 20,
					"gm_gc_army_headgear_hat_80_grn", 20,
					"gm_gc_bgs_headgear_hat_80_gry", 20,

					"gm_gc_army_headgear_hat_90_str", 20,
					"gm_gc_army_headgear_hat_90_sgr", 20,
					"gm_gc_army_headgear_hat_90_bg", 20,

					"gm_ge_headgear_hat_beanie_blk", 10,

					"gm_pl_army_headgear_cap_80_moro", 20
				};
			};
			class Berets
			{
				displayname = "Berets";
				realm = "cfgWeapons";
				content[] =
				{
					"gm_gc_headgear_beret_blk", 200,
					"gm_gc_headgear_beret_orn", 200,
					"gm_gc_headgear_beret_str", 200,

					"gm_gc_headgear_beret_officer_blk", 200,
					"gm_gc_headgear_beret_officer_orn", 200,
					"gm_gc_headgear_beret_officer_str", 200,

					"gm_pl_headgear_beret_bdx", 200,
					"gm_pl_headgear_beret_blu", 200,
					"gm_pl_headgear_beret_blk", 200
				};
			};
			class Vests
			{
				displayname = "Vests";
				realm = "cfgWeapons";
				content[] =
				{
					"gm_gc_army_vest_80_belt_str",100,
					"gm_gc_bgs_vest_80_border_str",100,
					"gm_gc_army_vest_80_at_str",100,
					"gm_gc_army_vest_80_leader_str",100,
					"gm_gc_army_vest_80_lmg_str",100,
					"gm_gc_army_vest_80_rifleman_str",100,

					"gm_gc_vest_combatvest3_str",100,
					"gm_gc_vest_combatvest3_pol",100,

					"gm_gc_army_vest_bespa_80_none_str", 2000,

					"gm_gc_army_vest_bespa_80_belt_str", 2100,
					"gm_gc_army_vest_bespa_80_leader_str", 2100,
					"gm_gc_army_vest_bespa_80_lmg_str", 2100,
					"gm_gc_army_vest_bespa_80_rifleman_str", 2100,
					"gm_gc_army_vest_bespa_80_at_str", 2100,

					"gm_gc_army_vest_bespa_80_none_win", 2000,

					"gm_gc_army_vest_bespa_80_belt_win", 2100,
					"gm_gc_army_vest_bespa_80_leader_win", 2100,
					"gm_gc_army_vest_bespa_80_lmg_win", 2100,
					"gm_gc_army_vest_bespa_80_rifleman_win", 2100,
					"gm_gc_army_vest_bespa_80_at_win", 2100,

					"gm_gc_army_vest_bespa_90_officer_str", 2100,
					"gm_gc_army_vest_bespa_90_belt_str", 2080,
					"gm_gc_army_vest_bespa_90_leader_str", 2100,
					"gm_gc_army_vest_bespa_90_lmg_str", 2120,
					"gm_gc_army_vest_bespa_90_rifleman_str", 2100,
					"gm_gc_army_vest_bespa_90_at_str", 2100,

					"gm_gc_army_vest_bespa_90_officer_win", 2100,
					"gm_gc_army_vest_bespa_90_belt_win", 2080,
					"gm_gc_army_vest_bespa_90_leader_win", 2100,
					"gm_gc_army_vest_bespa_90_lmg_win", 2120,
					"gm_gc_army_vest_bespa_90_rifleman_win", 2100,
					"gm_gc_army_vest_bespa_90_at_win", 2100,

					"gm_gc_army_vest_90_officer_str", 100,
					"gm_gc_army_vest_90_belt_str", 80,
					"gm_gc_army_vest_90_leader_str", 100,
					"gm_gc_army_vest_90_lmg_str", 120,
					"gm_gc_army_vest_90_rifleman_str", 100,
					"gm_gc_army_vest_90_at_str", 100,

					"gm_pl_army_vest_80_rig_gry",60,
					"gm_pl_army_vest_80_crew_gry",60,
					"gm_pl_army_vest_80_rifleman_gry",100,
					"gm_pl_army_vest_80_rifleman_smg_gry",100,
					"gm_pl_army_vest_80_leader_gry",100,
					"gm_pl_army_vest_80_marksman_gry",100,
					"gm_pl_army_vest_80_mg_gry",100,
					"gm_pl_army_vest_80_at_gry",100,

					"gm_pl_army_vest_armor_01_akm_80_frog", 2300,
					"gm_pl_army_vest_armor_01_akm_80_blu", 2300,
					"gm_pl_army_vest_armor_01_akm_80_str", 2300,
					"gm_pl_army_vest_armor_01_akm_80_oli", 2300,
					"gm_pl_army_vest_armor_01_akm_80_bg", 2300,
					"gm_pl_army_vest_armor_01_akm_80_win", 2300
				};
			};
			class Uniforms
			{
				displayname = "Uniforms";
				realm = "cfgWeapons";
				content[] =
				{
					"gm_gc_army_uniform_soldier_80_str", 100,
					"gm_gc_army_uniform_soldier_gloves_80_str", 100,
					"gm_gc_army_uniform_soldier_80_blk", 100,
					"gm_gc_army_uniform_soldier_80_win", 100,
					"gm_gc_army_uniform_dress_80_gry", 100,
					"gm_gc_pol_uniform_dress_80_blu", 100,

					"gm_gc_army_uniform_soldier_90_str", 100,
					"gm_gc_army_uniform_soldier_rolled_90_str", 100,
					"gm_gc_army_uniform_soldier_90_sgr", 100,
					"gm_gc_army_uniform_soldier_rolled_90_sgr", 100,

					"gm_pl_army_uniform_soldier_80_moro", 100,
					"gm_pl_army_uniform_soldier_80_frog", 100,
					"gm_pl_army_uniform_soldier_rolled_80_moro", 100,
					"gm_pl_army_uniform_soldier_rolled_80_frog", 100,
					"gm_pl_army_uniform_soldier_autumn_80_moro", 100,
					"gm_pl_army_uniform_soldier_80_win", 100,

					"gm_gc_airforce_uniform_pilot_80_blu", 100,
					"gm_pl_airforce_uniform_pilot_80_gry", 100

				};
			};
			class Backpacks
			{
				displayname = "Backpacks";
				realm = "cfgVehicles";
				content[] =
				{
					"gm_gc_army_backpack_80_at_str", 300,
					"gm_gc_army_backpack_80_lmg_str", 300,
					"gm_gc_army_backpack_80_assaultpack_str", 300,
					"gm_gc_army_backpack_80_assaultpack_lmg_str", 300,

					"gm_pl_army_backpack_80_oli", 300,
					"gm_pl_army_backpack_at_80_gry", 300,

					"gm_fagot_launcher_weaponBag", 3500,

					"gm_backpack_rs9_parachute", 100
				};
			};
		};
		class Vehicles
		{
			displayName = "Vehicles";

			class Cars
			{
				displayname = "Cars";
				realm = "cfgVehicles";
				content[] =
				{
					"gm_gc_army_p601", 400,

					"gm_gc_army_uaz469_cargo", 600,
					"gm_pl_army_uaz469_cargo", 600,

					"gm_gc_army_uaz469_dshkm", 1600,

					"gm_gc_army_uaz469_spg9", 2800
				};
			};

			class Trucks
			{
				displayname = "Trucks";
				realm = "cfgVehicles";
				content[] =
				{
					"gm_gc_army_ural4320_cargo", 2000,
					"gm_gc_army_ural375d_cargo", 2000,
					"gm_gc_army_ural44202", 2000
				};
			};

			class Supply
			{
				restricted = 1;
				displayname = "Supply";
				realm = "cfgVehicles";
				content[] =
				{
					"gm_gc_army_ural4320_cargo", 5000,
					"gm_gc_army_ural4320_repair", 5000,
					"gm_gc_army_ural4320_reammo", 10000,
					"gm_gc_army_ural375d_refuel", 5000,
					"gm_gc_army_ural375d_medic", 5000,

					"gm_gc_army_shelterlakII_repair", 2500,
					"gm_gc_army_shelterlakII_medic", 2500,
					"gm_gc_army_shelterlakII_reammo", 5500
				};
			};

			class MHQs
			{
				displayname = "Mobile Spawn Points";
				realm = "cfgVehicles";
				content[] =
				{
					"gm_gc_army_btr60pu12", 16000,
					"gm_gc_army_brdm2um", 16000,

					"gm_gc_airforce_l410s_salon_wdl", 12000,

					"gm_gc_army_shelterlakII_standard", 4000,

					"gm_gc_army_t55ak",  23500,
					"gm_pl_army_t55ak",  23500
				};
			};

			class APC
			{
				displayname = "APC";
				realm = "cfgVehicles";
				content[] =
				{
					"gm_gc_army_bmp1sp2", 8000,
					"gm_pl_army_bmp1sp2", 8000,

					"gm_gc_army_bmp1p", 10000,

					"gm_gc_army_brdm2", 3500,
					"gm_pl_army_brdm2", 3500,

					"gm_gc_army_brdm2_9p133", 7500,
					"gm_pl_army_brdm2_9p133", 7500,

					"gm_gc_army_brdm2rkh", 4200,
					"gm_pl_army_brdm2rkh", 4200,

					"gm_gc_army_btr60pa", 5000,
					"gm_gc_army_btr60pa_dshkm", 5100,
					"gm_gc_army_btr60pb", 5500,

					"gm_pl_army_ot64a", 5500
				};
			};

			class AA
			{
				displayname = "AAA";
				realm = "cfgVehicles";
				content[] =
				{
					"gm_gc_army_zsu234v1", 15000
				};
			};

			class Armor
			{
				displayname = "Tanks";
				realm = "cfgVehicles";
				content[] =
				{
					"gm_gc_army_pt76b", 9000,

					"gm_gc_army_t55",  15000,
					"gm_pl_army_t55",  15000,

					"gm_gc_army_t55a",  20000,
					"gm_pl_army_t55a",  20000,

					"gm_gc_army_t55am2", 25000,

					"gm_gc_army_t55am2b",   34000
				};
			};

			class Artillery
			{
				displayname = "Artillery";
				realm = "cfgVehicles";
				content[] =
				{
					// "gm_gc_army_ural375d_mlrs_oli", 85000,
					"gm_gc_army_2s1_oli", 55000,
					"gm_gc_army_2p16_oli", 110000,
					"gm_gc_army_2b11", 20000
				};
			};

			class Helicopters
			{
				displayname = "Helicopters";
				realm = "cfgVehicles";
				content[] =
				{
					"gm_gc_airforce_mi2p_beg", 12000,
					"gm_gc_airforce_mi2sr", 12000,
					"gm_gc_airforce_mi2t_beg", 14000,
					"gm_gc_airforce_mi2us_beg", 15000,
					"gm_gc_airforce_mi2urn_beg", 31000,
					"gm_gc_civ_mi2r", 29000,

					"gm_pl_airforce_mi2ch_bgb", 14000,
					"gm_pl_airforce_mi2urp_bgb", 23000,
					"gm_pl_airforce_mi2urpg_bgb", 26000,
					"gm_pl_airforce_mi2urs_bgb", 15000
				};
			};

			class Planes
			{
				displayname = "Planes";
				realm = "cfgVehicles";
				content[] =
				{
					"gm_gc_airforce_l410t_wdl", 12000
				};
			};
		};
	};
};