class gm_wfor
{
	class wfor
	{
		class init {postInit = 1;};    // gm_wfor_fnc_init

		class accounting_server {};    // gm_wfor_fnc_accounting_server

		class gearBank_server {};      // gm_wfor_fnc_gearBank_server

		class shop_cart {};            // gm_wfor_fnc_shop_cart
		class shop_cart_add {};        // gm_wfor_fnc_shop_cart_add
		class shop_cart_show {};       // gm_wfor_fnc_shop_cart_show
		class shop_displayContent {};  // gm_wfor_fnc_shop_displayContent
		class shop_init {};            // gm_wfor_fnc_shop_init
		class shop_purchase {};        // gm_wfor_fnc_shop_purchase
		class shop_updateTotal {};     // gm_wfor_fnc_shop_updateTotal

		class personalCustomizer {};   // gm_wfor_fnc_personalCustomizer

		class tutorial {};             // gm_wfor_fnc_tutorial
		class toggleSpawnPoint {};     // gm_wfor_fnc_toggleSpawnPoint
		class toggleCamoNet {};        // gm_wfor_fnc_toggleCamoNet
		class transferMoney {};        // gm_wfor_fnc_transferMoney
		class transferMoney_action {}; // gm_wfor_fnc_transferMoney_action

		class squadManagement {};        // gm_wfor_fnc_squadManagement
		class squadManagement_create {}; // gm_wfor_fnc_squadManagement_create

		class vehicle_setup {};          // gm_wfor_fnc_vehicle_setup
		class handleVehicleLoadout {};   // gm_wfor_fnc_handleVehicleLoadout
		
		class setupStart {};             // gm_wfor_fnc_setupStart
	};
};